output "connect_computer_to_cluster" {
  description = "Configure your computer to communicate with your cluster"
  value       = join("", ["aws eks update-kubeconfig ", "--region ", var.region, " --name ", aws_eks_cluster.tfletcher_eks_cluster.name])
}

output "cluster_name" {
  description = "EKS cluster Name."
  value       = aws_eks_cluster.tfletcher_eks_cluster.name
}

output "endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.tfletcher_eks_cluster.endpoint
}


output "kubeconfig-certificate-authority-data" {
  description = "kubectl config generated by the eks cluster"
  value       = aws_eks_cluster.tfletcher_eks_cluster.certificate_authority[0].data
}
